services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env.development
    depends_on:
      - postgres
      - redis
      - migrations
    restart: always

  postgres:
    image: postgres
    env_file:
      - .env.development
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "run", "drizzle:migrate"]
    env_file:
      - .env.development
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:
